version: "3.9"
services:
  consul-server1:
    image: ${CONSUL_IMAGE:-consul:local}
    container_name: consul-server-1
    restart: always
    volumes:
      - ./config/server1.json:/consul/config/server1.json:ro

      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - '8500:8500'
      - '8501:8501'

  consul-server2:
    image: ${CONSUL_IMAGE:-consul:local}
    container_name: consul-server-2
    restart: always
    volumes:
      - ./config/server2.json:/consul/config/server2.json:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - '8600:8500'
      - '8601:8501'

networks:
  consul:
    internal: false
    driver:
      bridge
    driver_opts:
      enable_icc: "true"
      enable_ip_masquerade: "true"

