version: "3.9"
services:
  consul-server1:
    image: consul:local
    container_name: consul-server-1
    restart: always
    volumes:
      - ./config/server1.json:/consul/config/server1.json:ro

      - ./certs/cluster-a/:/consul/config/certs/:ro
    networks:
      - consul
    environment:
      - CONSUL_HCP_ENABLED=true
      - CONSUL_HCP_MANAGED_RUNTIME=true
    ports:
      - '8501:8501'

  consul-server2:
    image: consul:local
    container_name: consul-server-2
    restart: always
    volumes:
      - ./config/server2.json:/consul/config/server2.json:ro
      - ./certs/cluster-b/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - '8601:8501'

networks:
  consul:
    internal: false
    driver:
      bridge
    driver_opts:
      enable_icc: "true"
      enable_ip_masquerade: "true"

